name: provider_todo
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.0
  provider: ^6.1.2
  path: ^1.9.0
  google_fonts: ^6.2.1
  flutter_signin_button: ^2.0.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  validatorless: ^1.2.3
  flutter_overlay_loader: ^2.0.0
  google_sign_in: ^6.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: TodoListIcons
      fonts:
        - asset: assets/fonts/TodoListIcons.ttf