// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2smiKVF4Lr83ZYDwMr-xsAF4nabv2A3Q',
    appId: '1:683974365463:android:71058118a5935474e0a752',
    messagingSenderId: '683974365463',
    projectId: 'todo-list-provider-10e6b',
    storageBucket: 'todo-list-provider-10e6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD22hWBvgQvsPRmiZZRUCvRs1uvzl9TdOk',
    appId: '1:683974365463:ios:a7e8e77e060b5f30e0a752',
    messagingSenderId: '683974365463',
    projectId: 'todo-list-provider-10e6b',
    storageBucket: 'todo-list-provider-10e6b.firebasestorage.app',
    iosClientId: '683974365463-bfgo3evq8dm0p4c03p41pqqtce0cs17b.apps.googleusercontent.com',
    iosBundleId: 'br.com.suamirochadev.providerTodo',
  );
}
